In [ ]:
import math as m
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from pandas import ExcelWriter
from pandas import ExcelFile
from datetime import datetime

Table = pd.read_csv("INFORMACION_SOCIODEMOGRAFICA.csv")
T8 = pd.read_csv(pathwork+namedata[7]+'.csv')
n8,m8=T8.shape

"""
#Crear tablas para procesos
#T1_sort=T1.sort_values("process_id")
#Hacemos una serie con los valores que no son terminados en la misma sucursal
slayproc=T1[T1["initial_branch_id"]!=T1["last_branch_id"]]["process_id"]
sn,=slayproc.shape
T1_clean=T1.copy()
#Luego los borramos
for i in range(0,sn):
    T1_clean=T1_clean.drop(slayproc.index[i])
#Limpiamos T2 de esos procesos
T2_clean=T2.copy()
slayproc2=np.array([])
#Ubicamos esos procesos en la tabla 2
for i in range(0,sn):
    slayproc2=np.append(slayproc2,(T2_clean[T1["process_id"][slayproc.index[i]]==T2_clean["process_id"]].index))
#Luego los borramos
sn2=len(slayproc2)
for i in range(0,sn2):
    T2_clean=T2_clean.drop(slayproc2[i])
    
#Limpiamos T3 de esos procesos
T3_clean=T3.copy()
slayproc3=np.array([])
#Ubicamos esos procesos en la tabla 3
for i in range(0,sn):
    slayproc3=np.append(slayproc3,(T3_clean[T1["process_id"][slayproc.index[i]]==T3_clean["process_id"]].index))
#Luego los borramos
sn3=len(slayproc3)
for i in range(0,sn):
    T3_clean=T3_clean.drop(slayproc3[i])
#Ahora creamos las tablas por sucursales
T1_sub=list()
for i in range(0,n8):
    T1_sub.append(T1_clean[T1_clean["initial_branch_id"]==T8["qf_branch_id"][i]])

#T2_sub=list()
#for i in range(0,n8):
#    T2_sub.append(T2_clean[T2_clean["qf_branch_id"]==T8["qf_branch_id"][i]])

#T3_sub=list()
#for i in range(0,n8):
#    T3_sub.append(T3_clean[T3_clean["initial_branch_id"]==T8["qf_branch_id"][i]])
#Tiempo para 1

for i in range(0,n8):
    time_up       = T1_sub[i]["arrival_dt"].values
    time_up_split = np.array([tt.split(" ") for tt in time_up])
    time          = np.array([tt.split(":") for tt in time_up_split[:,1]],dtype="float64")
    date          = np.array([tt.split("-") for tt in time_up_split[:,0]])
    T1_sub[i].insert(loc=1, column='arrival_month', value=date[:,1])
    #T1_sub[i].insert(loc=2, column='d_arrival', value=date[:,2])
    #T1_sub[i].insert(loc=3, column='hour_arrival', value=time[:,0])
    #T1_sub[i].insert(loc=4, column='min_arrival',  value=time[:,1])
    #T1_sub[i].insert(loc=5, column='seg_arrival',  value=time[:,2])

#for i in range(0,n8):
#    time_up       = T1_sub[i]["last_update_dt"].values
#    time_up_split = np.array([tt.split(" ") for tt in time_up])
#    time          = np.array([tt.split(":") for tt in time_up_split[:,1]],dtype="float64")
#    date          = np.array([tt.split("-") for tt in time_up_split[:,0]])
#    T1_sub[i].insert(loc=12, column='m_last', value=date[:,1])
#    T1_sub[i].insert(loc=13, column='d_last', value=date[:,2])
#    T1_sub[i].insert(loc=14, column='hour_last', value=time[:,0])
#    T1_sub[i].insert(loc=15, column='min_last',  value=time[:,1])
#    T1_sub[i].insert(loc=16, column='seg_last',  value=time[:,2])

for i in range(0,n8):
    namesave="T1_branch_"+str(T8["qf_branch_id"][i])
    T1_sub[i].sort_values("process_id").to_csv(pathwork+'datos_branch/'+namesave+'.csv', sep=',', index=False)
    #namesave="T2_branch_"+str(T8["qf_branch_id"][i])
    #T2_sub[i].sort_values("process_id").to_csv(pathwork+'datos_branch/'+namesave+'.csv', sep=',', index=False)
    #namesave="T3_branch_"+str(T8["qf_branch_id"][i])
    #T3_sub[i].sort_values("process_id").to_csv(pathwork+'datos_branch/'+namesave+'.csv', sep=',', index=False)
"""

In [312]:
test  = T1_sub[0]["arrival_dt"].values
test2 = np.array([tt.split(" ") for tt in test])
date1  = test2[:,0]
time1  = test2[:,1]
time_s= np.array([tt.split(":") for tt in time],dtype="float64")
date = np.array([tt.split("-") for tt in date1])
#test2 = np.array(test2,dtype='datetime64[us]').astype('datetime64[D]')

array([['2017', '10', '25'],
       ['2017', '10', '25'],
       ['2017', '10', '25'],
       ...,
       ['2017', '10', '25'],
       ['2017', '10', '25'],
       ['2017', '10', '25']],
      dtype='|S4')

In [1]:
import Funaux as F
F.aja()

ImportError: No module named 'Funaux'

In [3]:
T1_sub[1]

,process_id,arrival_dt,initialservice_id,initial_branch_id,customer_id,qcode,qnumber,last_proc_status,last_update_dt,last_service_id,last_branch_id,last_step_id,resolution
169,96254885,2017-10-25 10:48:21.530000,2316,184,6054085,S,316,8,2017-10-25 11:22:56.910000,2316,184,342915551,0
299,96260010,2017-10-25 10:59:10.380000,2316,184,4952886,S,322,8,2017-10-25 11:28:03.003000,2316,184,342924312,0
390,96263324,2017-10-25 11:06:19.250000,2319,184,NaN,A,814,8,2017-10-25 11:17:49.027000,2319,184,342906861,0
433,96264739,2017-10-25 11:09:29.697000,2316,184,1243211,S,328,8,2017-10-25 11:45:12.280000,2316,184,342952326,0
508,96268306,2017-10-25 11:17:30.580000,2316,184,3954588,S,331,8,2017-10-25 11:52:28.223000,2316,184,342962323,0
602,96272344,2017-10-25 11:26:21.380000,2314,184,2725924,M,102,8,2017-10-25 11:28:58.737000,2314,184,342925880,0
630,96273349,2017-10-25 11:28:39.100000,2316,184,NaN,S,338,8,2017-10-25 11:57:33.313000,2316,184,342968451,0
652,96274082,2017-10-25 11:30:27.470000,2316,184,3475995,S,339,8,2017-10-25 11:56:10.090000,2316,184,342966804,0
1647,96313932,2017-10-25 13:59:54.673000,2316,184,NaN,S,352,8,2017-10-25 14:40:17.600000,2316,184,343152485,0
1707,96316627,2017-10-25 14:05:00.207000,2316,184,5873702,S,356,4,2017-10-25 15:00:01.347000,2316,184,343183452,3
1795,96319888,2017-10-25 14:11:55.197000,2316,184,1081085,S,361,8,2017-10-25 14:56:56.693000,2316,184,343178533,0
1802,96320109,2017-10-25 14:12:22.283000,2313,184,2432538,J,334,8,2017-10-25 14:36:44.167000,2313,184,343147018,0
1804,96320216,2017-10-25 14:12:37.330000,2316,184,1082559,S,362,8,2017-10-25 15:12:56.650000,2316,184,343204759,0
1871,96323183,2017-10-25 14:18:58.027000,2321,184,1098330,Q,530,8,2017-10-25 14:42:48.200000,2321,184,343156309,0
1904,96324391,2017-10-25 14:21:29.007000,2321,184,98422,Q,531,8,2017-10-25 14:45:31.387000,2321,184,343161029,0
1934,96325213,2017-10-25 14:23:16.667000,2316,184,3414800,S,371,8,2017-10-25 15:05:51.640000,2316,184,343193061,0
1949,96325777,2017-10-25 14:24:28.077000,2312,184,1737955,E,524,8,2017-10-25 15:04:04.120000,2312,184,343190161,0
1966,96326369,2017-10-25 14:25:45.843000,2316,184,1655512,S,373,8,2017-10-25 15:11:01.247000,2316,184,343201447,0
1981,96326880,2017-10-25 14:26:48.620000,2319,184,1161741,A,821,8,2017-10-25 14:46:40.183000,2319,184,343162780,0
2184,96334984,2017-10-25 14:43:11.280000,2316,184,4251624,S,380,8,2017-10-25 15:15:32.343000,2316,184,343209749,0
2202,96335635,2017-10-25 14:44:27.767000,2316,184,2786954,S,382,4,2017-10-25 15:30:04.357000,2316,184,343234023,3
2330,96340652,2017-10-25 14:54:46.777000,2313,184,1811629,J,342,8,2017-10-25 15:29:57.473000,2313,184,343233239,0
2349,96341471,2017-10-25 14:56:31.980000,2322,184,1188874,O,405,4,2017-10-25 16:15:01.437000,2319,184,343304932,3
2374,96342334,2017-10-25 14:58:16.750000,2316,184,1246656,S,387,8,2017-10-25 15:29:44.183000,2316,184,343232839,0
2433,96344665,2017-10-25 15:03:09.573000,2316,184,9637139,S,390,8,2017-10-25 15:31:09.130000,2316,184,343236427,0
2436,96344799,2017-10-25 15:03:29.493000,2316,184,9637139,S,391,8,2017-10-25 15:27:03.587000,2316,184,343228489,0
2469,96345998,2017-10-25 15:05:58.480000,2319,184,3923963,A,823,8,2017-10-25 15:23:17.950000,2319,184,343222418,0
2564,96350667,2017-10-25 15:15:30.480000,2321,184,1166773,Q,538,4,2017-10-25 15:30:08.130000,2321,184,343234668,3
2604,96352704,2017-10-25 15:19:50.133000,2321,184,1081174,Q,539,8,2017-10-25 15:41:12.847000,2321,184,343252616,0
2708,96357013,2017-10-25 15:28:50.357000,2316,184,2187484,S,409,8,2017-10-25 15:49:54.763000,2316,184,343267640,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2393455,96198974,2017-10-25 08:44:42.520000,2316,184,7637433,S,236,8,2017-10-25 08:50:11.100000,2316,184,342675703,0
2393458,96199046,2017-10-25 08:44:54.787000,2316,184,1082454,S,237,8,2017-10-25 08:54:22.780000,2316,184,342679861,0
2393479,96199925,2017-10-25 08:47:43.957000,2319,184,8404275,A,800,8,2017-10-25 08:56:55.250000,2319,184,342682561,0
2393488,96200141,2017-10-25 08:48:30.303000,2316,184,9308900,S,240,8,2017-10-25 09:24:21.553000,2312,184,342722268,0
2393504,96200757,2017-10-25 08:50:30.813000,2321,184,1079723,Q,502,8,2017-10-25 08:57:01.887000,2321,184,342682677,0
2393521,96201654,2017-10-25 08:53:23.890000,2316,184,1166441,S,244,8,2017-10-25 09:19:39.827000,2316,184,342715573,0
2393556,96203322,2017-10-25 08:57:40.467000,2312,184,1080135,E,504,8,2017-10-25 09:42:48.247000,2312,184,342750580,0
2393573,96204257,2017-10-25 09:00:04.897000,2321,184,1355134,Q,504,8,2017-10-25 09:03:03.440000,2321,184,342690647,0
2393673,96208134,2017-10-25 09:06:59.200000,2322,184,2836244,O,400,8,2017-10-25 09:19:14.600000,2313,184,342714932,0
2393724,96210202,2017-10-25 09:11:12.097000,2319,184,1367987,A,803,8,2017-10-25 09:21:49.633000,2319,184,342718648,0
2393748,96210900,2017-10-25 09:12:36.470000,2321,184,1999308,Q,506,8,2017-10-25 09:38:50.527000,2321,184,342744576,0
2393797,96212914,2017-10-25 09:16:51.570000,2316,184,3592171,S,261,8,2017-10-25 09:50:49.960000,2316,184,342763188,0
2393886,96216358,2017-10-25 09:24:19.867000,2313,184,190347,J,312,8,2017-10-25 09:45:47.150000,2319,184,342755538,0
2393895,96216870,2017-10-25 09:25:26.773000,2319,184,1382509,A,804,8,2017-10-25 09:52:00.467000,2319,184,342764893,0
2393999,96221326,2017-10-25 09:35:16.647000,2318,184,1801171,L,900,8,2017-10-25 09:38:17.470000,2318,184,342743727,0
2394049,96223290,2017-10-25 09:39:35.033000,2316,184,NaN,S,271,8,2017-10-25 10:09:46.240000,2316,184,342791006,0
2394103,96225363,2017-10-25 09:44:09.877000,2316,184,1079537,S,275,8,2017-10-25 10:13:27.480000,2316,184,342796178,0
2394158,96227390,2017-10-25 09:48:47.660000,2316,184,1118621,S,277,8,2017-10-25 10:23:34.007000,2316,184,342812571,0
2394208,96229805,2017-10-25 09:54:19.510000,2314,184,1628639,M,100,8,2017-10-25 10:12:33.040000,2314,184,342794873,0
2394216,96230183,2017-10-25 09:55:09.573000,2319,184,NaN,A,806,8,2017-10-25 10:12:36.060000,2319,184,342794957,0
2394233,96231124,2017-10-25 09:57:18.607000,2316,184,1114254,S,285,8,2017-10-25 10:25:12.660000,2316,184,342815098,0
2394245,96231471,2017-10-25 09:58:05.407000,2316,184,NaN,S,287,8,2017-10-25 10:25:38.423000,2316,184,342815784,0
2394247,96231681,2017-10-25 09:58:35.753000,2319,184,1152306,A,808,8,2017-10-25 10:18:46.503000,2319,184,342804916,0
2394340,96235951,2017-10-25 10:08:50.890000,2312,184,NaN,E,509,8,2017-10-25 10:39:09.903000,2312,184,342839180,0
2394388,96237854,2017-10-25 10:13:25.073000,2316,184,2186607,S,292,4,2017-10-25 10:45:10.503000,2316,184,342850035,3
2394482,96241975,2017-10-25 10:22:13.420000,2316,184,1131843,S,302,8,2017-10-25 10:55:17.730000,2316,184,342867149,0
2394542,96244464,2017-10-25 10:27:18.777000,2316,184,8226814,S,306,8,2017-10-25 11:06:43.787000,2316,184,342887576,0
2394593,96246510,2017-10-25 10:31:22.340000,2321,184,1108795,Q,517,4,2017-10-25 11:15:05.617000,2321,184,342901992,3
2394608,96247298,2017-10-25 10:32:58.383000,2313,184,1342782,J,324,8,2017-10-25 11:12:34.967000,2313,184,342897296,0
2394613,96247530,2017-10-25 10:33:26.120000,2316,184,1555297,S,311,8,2017-10-25 11:13:11.430000,2316,184,342898343,0

In [323]:
time[0]

array([ 10.  ,  39.  ,  22.71])